Added models for apps
ImaWalkerr/dealership pull request #1
Opened 2022-06-26 17:08 UTC by ImaWalkerr

Also added admin base register

2022-06-26 17:38 UTC, tenatarika requested changes

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +    name = models.CharField(max_length=255, blank=True, verbose_name='Dealership name')
А как  Дилершипы могут быть без имени ?

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +    balance = models.FloatField(default=0, verbose_name='Dealership balance')
баланс может быть только положительным

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +        'CarDealerShipHistorySales', verbose_name='Car history sales', related_name='dealership_car_history_sales'
CarDealerShipHistorySales нужно указывать в параметре through

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +    cars_list = models.ManyToManyField(
историю можно хранить сразу в промежуточной таблице  между car и DealerShip поэтому  CarDealerShipHistorySales не нужна

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +    car = models.ForeignKey('Car', on_delete=models.CASCADE, verbose_name='Car')
Продумай удаление

По заданию у нас безопасное удаление, каскады не везде нужны

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +    car_dealer = models.ManyToManyField(to='dealer.Dealer', verbose_name='Car dealer', related_name='car_dealer')
вынеси промежуточную таблицу в through

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +    car_color = models.CharField(max_length=255, blank=True, verbose_name='Car color')
цвета вынеси в enum и енамы храни в коре

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +    car_year = models.PositiveIntegerField(default=None, blank=True, verbose_name='Car year')
Год будет от 1900 +

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +    car_interior_color = models.CharField(max_length=255, blank=True, verbose_name='Car interior color')
Типы салона авто вынеси в енам

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +    car_mileage = models.IntegerField(default=0, blank=True, verbose_name='Car mileage')
пробег не может быть отрицательным

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +    car_gearbox = models.CharField(max_length=255, blank=True, choices=GEARBOX, verbose_name='Car drive')
коробку передач тоже в енамы

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +
добавь булеан филд ,  является ли это электрокаром

2022-06-26 17:38 UTC, tenatarika commented on src/car_dealership/models.py
> +    car_engine_volume = models.FloatField(default=None, blank=True, verbose_name='Car engine volume')
Все типы машин в енамы

2022-06-26 17:38 UTC, tenatarika commented on src/customer/models.py
> +class CustomerHistory(BaseModel):
Offer можно хранить сразу тут. И поменяй название таблицы на CustomerCar тогда

2022-06-26 17:38 UTC, tenatarika commented on src/customer/models.py
> +    car_info = models.JSONField()
добавь дефаулт значение

2022-06-26 17:38 UTC, tenatarika commented on src/customer/models.py
> +    action_info = models.TextField(max_length=5000, verbose_name='Action description')
Зачем эти поля?

2022-06-26 17:38 UTC, tenatarika commented on src/core/abstract_field.py
> +
добавь дату удаления инстанса

2022-06-26 17:38 UTC, tenatarika commented on src/dealer/models.py
> +    founding_date = models.DateField(default=None, blank=True, verbose_name='Dealer founding date')
дата создания есть в абстрактном классе

2022-06-26 17:38 UTC, tenatarika commented on src/dealer/models.py
> +    customers_count = models.ManyToManyField(
Тут модно позитивным интом обойтись

2022-06-26 17:38 UTC, tenatarika commented on src/dealer/models.py
> +    dealer_sales_history = models.ManyToManyField(
историю можно вести в m2m модели между дилером и машиной

2022-06-26 17:38 UTC, tenatarika commented on src/dealer/models.py
> +class Dealer(BaseModel):
Добавь  дилеру количество машин в его распоряжении

2022-06-26 17:38 UTC, tenatarika commented on src/dealer/models.py
> +    car_price = MoneyField(
DealerPrice и DealerSalesHistory можно смержить в одну таблицу между дилером и машиной

2022-06-27 09:13 UTC, ImaWalkerr commented on src/dealer/models.py
> +    car_price = MoneyField(
+

2022-06-27 09:13 UTC, ImaWalkerr commented on src/dealer/models.py
> +class Dealer(BaseModel):
done

2022-06-27 09:15 UTC, ImaWalkerr commented on src/dealer/models.py
> +    dealer_sales_history = models.ManyToManyField(
done

2022-06-27 09:15 UTC, ImaWalkerr commented on src/dealer/models.py
> +    customers_count = models.ManyToManyField(
done

2022-06-27 09:15 UTC, ImaWalkerr commented on src/customer/models.py
> +    action_info = models.TextField(max_length=5000, verbose_name='Action description')
+

2022-06-27 09:16 UTC, ImaWalkerr commented on src/car_dealership/models.py
> +
done

2022-06-27 09:16 UTC, ImaWalkerr commented on src/car_dealership/models.py
> +    car_mileage = models.IntegerField(default=0, blank=True, verbose_name='Car mileage')
done

2022-06-27 09:17 UTC, ImaWalkerr commented on src/car_dealership/models.py
> +    balance = models.FloatField(default=0, verbose_name='Dealership balance')
done

2022-06-27 09:17 UTC, ImaWalkerr commented on src/car_dealership/models.py
> +    name = models.CharField(max_length=255, blank=True, verbose_name='Dealership name')
XD

2022-06-27 10:01 UTC, ImaWalkerr commented on src/dealer/models.py
> +    founding_date = models.DateField(default=None, blank=True, verbose_name='Dealer founding date')
в задании дата основания автосалона стоит) поидее она нужна в таком виде

2022-06-27 13:58 UTC, tenatarika approved these changes
чотка

2022-06-28 08:57 UTC, closed without merging